/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\vuepress\\vuepress-github\\docs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-35204b8c",
    path: "/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35204b8c").then(next)
    },
  },
  {
    name: "v-1215a3cf",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1215a3cf").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-2c6c8e00",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c6c8e00").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-5387826c",
    path: "/aboutless.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5387826c").then(next)
    },
  },
  {
    name: "v-7fa37fb5",
    path: "/pc/p-a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7fa37fb5").then(next)
    },
  },
  {
    name: "v-62ea3633",
    path: "/pc/p-b.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62ea3633").then(next)
    },
  },
  {
    name: "v-7ba60f92",
    path: "/pc/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ba60f92").then(next)
    },
  },
  {
    path: "/pc/index.html",
    redirect: "/pc/"
  },
  {
    name: "v-437744df",
    path: "/phone/phone-b.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-437744df").then(next)
    },
  },
  {
    name: "v-4f90747e",
    path: "/phone/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f90747e").then(next)
    },
  },
  {
    path: "/phone/index.html",
    redirect: "/phone/"
  },
  {
    name: "v-e1449282",
    path: "/phone/phone-c.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e1449282").then(next)
    },
  },
  {
    name: "v-17cd735c",
    path: "/secondless/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17cd735c").then(next)
    },
  },
  {
    path: "/secondless/index.html",
    redirect: "/secondless/"
  },
  {
    name: "v-00ea391a",
    path: "/secondless/w-a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00ea391a").then(next)
    },
  },
  {
    name: "v-74767873",
    path: "/secondless/w-a/Date%E7%B1%BB%E5%9E%8B%EF%BC%9A%E6%97%B6%E9%97%B4%E5%92%8C%E6%97%A5%E6%9C%9F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74767873").then(next)
    },
  },
  {
    path: "/secondless/w-a/Date类型：时间和日期.html",
    redirect: "/secondless/w-a/Date%E7%B1%BB%E5%9E%8B%EF%BC%9A%E6%97%B6%E9%97%B4%E5%92%8C%E6%97%A5%E6%9C%9F.html"
  },
  {
    path: "/secondless/w-a/Date类型：时间和日期.html",
    redirect: "/secondless/w-a/Date%E7%B1%BB%E5%9E%8B%EF%BC%9A%E6%97%B6%E9%97%B4%E5%92%8C%E6%97%A5%E6%9C%9F.html"
  },
  {
    name: "v-4630ecb1",
    path: "/pc/p-c.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4630ecb1").then(next)
    },
  },
  {
    name: "v-5622dfda",
    path: "/secondless/w-a/Function%E7%B1%BB%E5%9E%8B%EF%BC%9A%E5%87%BD%E6%95%B0%E8%BF%9B%E9%98%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5622dfda").then(next)
    },
  },
  {
    path: "/secondless/w-a/Function类型：函数进阶.html",
    redirect: "/secondless/w-a/Function%E7%B1%BB%E5%9E%8B%EF%BC%9A%E5%87%BD%E6%95%B0%E8%BF%9B%E9%98%B6.html"
  },
  {
    path: "/secondless/w-a/Function类型：函数进阶.html",
    redirect: "/secondless/w-a/Function%E7%B1%BB%E5%9E%8B%EF%BC%9A%E5%87%BD%E6%95%B0%E8%BF%9B%E9%98%B6.html"
  },
  {
    name: "v-d73347ee",
    path: "/secondless/w-a/javascript%E5%87%BD%E6%95%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d73347ee").then(next)
    },
  },
  {
    path: "/secondless/w-a/javascript函数.html",
    redirect: "/secondless/w-a/javascript%E5%87%BD%E6%95%B0.html"
  },
  {
    path: "/secondless/w-a/javascript函数.html",
    redirect: "/secondless/w-a/javascript%E5%87%BD%E6%95%B0.html"
  },
  {
    name: "v-10de5a02",
    path: "/phone/phone-a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-10de5a02").then(next)
    },
  },
  {
    name: "v-57c86994",
    path: "/secondless/w-a/javascript%E5%9F%BA%E7%A1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-57c86994").then(next)
    },
  },
  {
    path: "/secondless/w-a/javascript基础.html",
    redirect: "/secondless/w-a/javascript%E5%9F%BA%E7%A1%80.html"
  },
  {
    path: "/secondless/w-a/javascript基础.html",
    redirect: "/secondless/w-a/javascript%E5%9F%BA%E7%A1%80.html"
  },
  {
    name: "v-2353c608",
    path: "/secondless/w-a/javascript%E5%AF%B9%E8%B1%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2353c608").then(next)
    },
  },
  {
    path: "/secondless/w-a/javascript对象.html",
    redirect: "/secondless/w-a/javascript%E5%AF%B9%E8%B1%A1.html"
  },
  {
    path: "/secondless/w-a/javascript对象.html",
    redirect: "/secondless/w-a/javascript%E5%AF%B9%E8%B1%A1.html"
  },
  {
    name: "v-596307a2",
    path: "/secondless/w-a/javascript%E6%95%B0%E7%BB%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-596307a2").then(next)
    },
  },
  {
    path: "/secondless/w-a/javascript数组.html",
    redirect: "/secondless/w-a/javascript%E6%95%B0%E7%BB%84.html"
  },
  {
    path: "/secondless/w-a/javascript数组.html",
    redirect: "/secondless/w-a/javascript%E6%95%B0%E7%BB%84.html"
  },
  {
    name: "v-de1c72cc",
    path: "/secondless/w-a/%E6%B5%81%E7%A8%8B%E6%8E%A7%E5%88%B6%E8%AF%AD%E5%8F%A5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-de1c72cc").then(next)
    },
  },
  {
    path: "/secondless/w-a/流程控制语句.html",
    redirect: "/secondless/w-a/%E6%B5%81%E7%A8%8B%E6%8E%A7%E5%88%B6%E8%AF%AD%E5%8F%A5.html"
  },
  {
    path: "/secondless/w-a/流程控制语句.html",
    redirect: "/secondless/w-a/%E6%B5%81%E7%A8%8B%E6%8E%A7%E5%88%B6%E8%AF%AD%E5%8F%A5.html"
  },
  {
    name: "v-12e6c9f7",
    path: "/secondless/w-a/%E5%8C%BF%E5%90%8D%E5%87%BD%E6%95%B0%E5%92%8C%E9%97%AD%E5%8C%85.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12e6c9f7").then(next)
    },
  },
  {
    path: "/secondless/w-a/匿名函数和闭包.html",
    redirect: "/secondless/w-a/%E5%8C%BF%E5%90%8D%E5%87%BD%E6%95%B0%E5%92%8C%E9%97%AD%E5%8C%85.html"
  },
  {
    path: "/secondless/w-a/匿名函数和闭包.html",
    redirect: "/secondless/w-a/%E5%8C%BF%E5%90%8D%E5%87%BD%E6%95%B0%E5%92%8C%E9%97%AD%E5%8C%85.html"
  },
  {
    name: "v-fe8bdd96",
    path: "/secondless/w-a/javascript%E8%BF%90%E7%AE%97%E7%AC%A6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fe8bdd96").then(next)
    },
  },
  {
    path: "/secondless/w-a/javascript运算符.html",
    redirect: "/secondless/w-a/javascript%E8%BF%90%E7%AE%97%E7%AC%A6.html"
  },
  {
    path: "/secondless/w-a/javascript运算符.html",
    redirect: "/secondless/w-a/javascript%E8%BF%90%E7%AE%97%E7%AC%A6.html"
  },
  {
    name: "v-1d6f685a",
    path: "/secondless/w-a/%E5%86%85%E7%BD%AE%E5%AF%B9%E8%B1%A1%EF%BC%9AGlobal%E3%80%81Math%E5%AF%B9%E8%B1%A1%EF%BC%8C%E5%8F%98%E9%87%8F%E3%80%81%E4%BD%9C%E7%94%A8%E5%9F%9F%E5%92%8C%E5%86%85%E5%AD%98%E9%97%AE%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d6f685a").then(next)
    },
  },
  {
    path: "/secondless/w-a/内置对象：Global、Math对象，变量、作用域和内存问题.html",
    redirect: "/secondless/w-a/%E5%86%85%E7%BD%AE%E5%AF%B9%E8%B1%A1%EF%BC%9AGlobal%E3%80%81Math%E5%AF%B9%E8%B1%A1%EF%BC%8C%E5%8F%98%E9%87%8F%E3%80%81%E4%BD%9C%E7%94%A8%E5%9F%9F%E5%92%8C%E5%86%85%E5%AD%98%E9%97%AE%E9%A2%98.html"
  },
  {
    path: "/secondless/w-a/内置对象：Global、Math对象，变量、作用域和内存问题.html",
    redirect: "/secondless/w-a/%E5%86%85%E7%BD%AE%E5%AF%B9%E8%B1%A1%EF%BC%9AGlobal%E3%80%81Math%E5%AF%B9%E8%B1%A1%EF%BC%8C%E5%8F%98%E9%87%8F%E3%80%81%E4%BD%9C%E7%94%A8%E5%9F%9F%E5%92%8C%E5%86%85%E5%AD%98%E9%97%AE%E9%A2%98.html"
  },
  {
    name: "v-057d6a1e",
    path: "/secondless/w-b.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-057d6a1e").then(next)
    },
  },
  {
    name: "v-0a109b22",
    path: "/secondless/w-c.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a109b22").then(next)
    },
  },
  {
    name: "v-6de531b2",
    path: "/web/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6de531b2").then(next)
    },
  },
  {
    path: "/web/index.html",
    redirect: "/web/"
  },
  {
    name: "v-544f4fdf",
    path: "/web/w-a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-544f4fdf").then(next)
    },
  },
  {
    name: "v-b2a3f302",
    path: "/web/w-b.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b2a3f302").then(next)
    },
  },
  {
    name: "v-0de685c2",
    path: "/web/w-c.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0de685c2").then(next)
    },
  },
  {
    name: "v-1ead3dbc",
    path: "/%E5%BC%80%E5%8F%91%E8%AE%B0%E5%BD%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ead3dbc").then(next)
    },
  },
  {
    path: "/开发记录.html",
    redirect: "/%E5%BC%80%E5%8F%91%E8%AE%B0%E5%BD%95.html"
  },
  {
    path: "/开发记录.html",
    redirect: "/%E5%BC%80%E5%8F%91%E8%AE%B0%E5%BD%95.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]