/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "睿晨网",
  "description": "睿晨网|睿晨编程|零基础学做网站、app、小程序就从这里开始",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/assets/img/favicon.png"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "睿晨网,睿晨编程,零基础学做网站,零基础学app,零基础学小程序"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "睿晨网,睿晨编程,阿东老师"
      }
    ]
  ],
  "pages": [
    {
      "title": "关于我们html",
      "frontmatter": {
        "navbar": true,
        "title": "关于我们html"
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-35204b8c",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 3,
          "title": "1.二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题2",
          "slug": "一级标题2"
        },
        {
          "level": 2,
          "title": "一级标题3",
          "slug": "一级标题3"
        },
        {
          "level": 2,
          "title": "一级标题4",
          "slug": "一级标题4"
        }
      ],
      "lastUpdated": "2023年3月1日星期三晚上7点24分",
      "lastUpdatedTimestamp": 1677669880000
    },
    {
      "title": "关于我们内页",
      "frontmatter": {
        "navbar": false,
        "sidebar": "auto",
        "title": "关于我们内页"
      },
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-2c6c8e00",
      "path": "/about/",
      "headers": [
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 3,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 2,
          "title": "一级标题2",
          "slug": "一级标题2"
        },
        {
          "level": 2,
          "title": "一级标题3",
          "slug": "一级标题3"
        }
      ],
      "lastUpdated": "2023年3月1日星期三下午12点33分",
      "lastUpdatedTimestamp": 1677645233000
    },
    {
      "title": "我是pc总页",
      "frontmatter": {
        "navbar": true,
        "title": "我是pc总页"
      },
      "regularPath": "/pc/",
      "relativePath": "pc/README.md",
      "key": "v-7ba60f92",
      "path": "/pc/",
      "lastUpdated": "2023年3月1日星期三下午12点33分",
      "lastUpdatedTimestamp": 1677645233000
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "睿晨编程",
        "tagline": "零基础转行学做网站、app、小程序",
        "actionText": "快速上手 →",
        "actionLink": "https://www.bilibili.com/video/BV1SW4y1L7i9/?vd_source=9a6ee0d7e6c1657e4a7381c1f8f18f4b",
        "features": [
          {
            "title": "需求人群",
            "details": "很多想转行，想接单做网站等需求的小白，不知道如何转行学编程的学员。"
          },
          {
            "title": "课程适合人群",
            "details": "零基础、其他行业转行学编程、想接私单(网站、小程序、app)、进一步提升自己知识能力的人。"
          },
          {
            "title": "课程体系",
            "details": "课程安排从基础入门开始，由网站开发到移动端小程序、APP的讲解。"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-1215a3cf",
      "path": "/",
      "lastUpdated": "2023年3月1日星期三下午12点33分",
      "lastUpdatedTimestamp": 1677645233000
    },
    {
      "title": "p-a页面",
      "frontmatter": {
        "title": "p-a页面"
      },
      "regularPath": "/pc/p-a.html",
      "relativePath": "pc/p-a.md",
      "key": "v-7fa37fb5",
      "path": "/pc/p-a.html",
      "headers": [
        {
          "level": 2,
          "title": "p-a页面二级标题1",
          "slug": "p-a页面二级标题1"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3"
        },
        {
          "level": 2,
          "title": "p-a页面二级标题2",
          "slug": "p-a页面二级标题2"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1-2"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2-2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3-2"
        }
      ],
      "lastUpdated": "2023年3月1日星期三下午12点33分",
      "lastUpdatedTimestamp": 1677645233000
    },
    {
      "title": "p-b页面",
      "frontmatter": {
        "title": "p-b页面"
      },
      "regularPath": "/pc/p-b.html",
      "relativePath": "pc/p-b.md",
      "key": "v-62ea3633",
      "path": "/pc/p-b.html",
      "headers": [
        {
          "level": 2,
          "title": "p-b页面二级标题1",
          "slug": "p-b页面二级标题1"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3"
        },
        {
          "level": 2,
          "title": "p-b页面二级标题2",
          "slug": "p-b页面二级标题2"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1-2"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2-2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3-2"
        }
      ],
      "lastUpdated": "2023年3月1日星期三下午12点33分",
      "lastUpdatedTimestamp": 1677645233000
    },
    {
      "title": "p-c页面",
      "frontmatter": {
        "title": "p-c页面"
      },
      "regularPath": "/pc/p-c.html",
      "relativePath": "pc/p-c.md",
      "key": "v-4630ecb1",
      "path": "/pc/p-c.html",
      "headers": [
        {
          "level": 2,
          "title": "p-c页面二级标题1",
          "slug": "p-c页面二级标题1"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3"
        },
        {
          "level": 2,
          "title": "p-c页面二级标题2",
          "slug": "p-c页面二级标题2"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1-2"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2-2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3-2"
        }
      ],
      "lastUpdated": "2023年3月1日星期三下午12点33分",
      "lastUpdatedTimestamp": 1677645233000
    },
    {
      "title": "我是phone总页",
      "frontmatter": {
        "navbar": true,
        "title": "我是phone总页"
      },
      "regularPath": "/phone/",
      "relativePath": "phone/README.md",
      "key": "v-4f90747e",
      "path": "/phone/",
      "lastUpdated": "2023年3月1日星期三下午12点33分",
      "lastUpdatedTimestamp": 1677645233000
    },
    {
      "title": "phone-a页面",
      "frontmatter": {
        "title": "phone-a页面"
      },
      "regularPath": "/phone/phone-a.html",
      "relativePath": "phone/phone-a.md",
      "key": "v-10de5a02",
      "path": "/phone/phone-a.html",
      "headers": [
        {
          "level": 2,
          "title": "phone-a页面二级标题1",
          "slug": "phone-a页面二级标题1"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3"
        },
        {
          "level": 2,
          "title": "phone-a页面二级标题2",
          "slug": "phone-a页面二级标题2"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1-2"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2-2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3-2"
        }
      ],
      "lastUpdated": "2023年3月1日星期三下午12点33分",
      "lastUpdatedTimestamp": 1677645233000
    },
    {
      "title": "phone-b页面",
      "frontmatter": {
        "title": "phone-b页面"
      },
      "regularPath": "/phone/phone-b.html",
      "relativePath": "phone/phone-b.md",
      "key": "v-437744df",
      "path": "/phone/phone-b.html",
      "headers": [
        {
          "level": 2,
          "title": "phone-b页面二级标题1",
          "slug": "phone-b页面二级标题1"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3"
        },
        {
          "level": 2,
          "title": "phone-b页面二级标题2",
          "slug": "phone-b页面二级标题2"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1-2"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2-2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3-2"
        }
      ],
      "lastUpdated": "2023年3月1日星期三下午12点33分",
      "lastUpdatedTimestamp": 1677645233000
    },
    {
      "title": "phone-c页面",
      "frontmatter": {
        "title": "phone-c页面"
      },
      "regularPath": "/phone/phone-c.html",
      "relativePath": "phone/phone-c.md",
      "key": "v-e1449282",
      "path": "/phone/phone-c.html",
      "headers": [
        {
          "level": 2,
          "title": "phone-c页面二级标题1",
          "slug": "phone-c页面二级标题1"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3"
        },
        {
          "level": 2,
          "title": "phone-c页面二级标题2",
          "slug": "phone-c页面二级标题2"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1-2"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2-2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3-2"
        }
      ],
      "lastUpdated": "2023年3月1日星期三下午12点33分",
      "lastUpdatedTimestamp": 1677645233000
    },
    {
      "title": "我是web总页",
      "frontmatter": {
        "navbar": true,
        "title": "我是web总页"
      },
      "regularPath": "/web/",
      "relativePath": "web/README.md",
      "key": "v-6de531b2",
      "path": "/web/",
      "lastUpdated": "2023年3月1日星期三下午12点33分",
      "lastUpdatedTimestamp": 1677645233000
    },
    {
      "title": "w-a页面",
      "frontmatter": {
        "title": "w-a页面"
      },
      "regularPath": "/web/w-a.html",
      "relativePath": "web/w-a.md",
      "key": "v-544f4fdf",
      "path": "/web/w-a.html",
      "headers": [
        {
          "level": 2,
          "title": "w-a页面二级标题1",
          "slug": "w-a页面二级标题1"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3"
        },
        {
          "level": 2,
          "title": "w-a页面二级标题2",
          "slug": "w-a页面二级标题2"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1-2"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2-2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3-2"
        }
      ],
      "lastUpdated": "2023年3月1日星期三下午12点33分",
      "lastUpdatedTimestamp": 1677645233000
    },
    {
      "title": "w-b页面",
      "frontmatter": {
        "title": "w-b页面"
      },
      "regularPath": "/web/w-b.html",
      "relativePath": "web/w-b.md",
      "key": "v-b2a3f302",
      "path": "/web/w-b.html",
      "headers": [
        {
          "level": 2,
          "title": "w-b页面二级标题1",
          "slug": "w-b页面二级标题1"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3"
        },
        {
          "level": 2,
          "title": "w-b页面二级标题2",
          "slug": "w-b页面二级标题2"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1-2"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2-2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3-2"
        }
      ],
      "lastUpdated": "2023年3月1日星期三下午12点33分",
      "lastUpdatedTimestamp": 1677645233000
    },
    {
      "title": "w-c页面",
      "frontmatter": {
        "title": "w-c页面"
      },
      "regularPath": "/web/w-c.html",
      "relativePath": "web/w-c.md",
      "key": "v-0de685c2",
      "path": "/web/w-c.html",
      "headers": [
        {
          "level": 2,
          "title": "w-c页面二级标题1",
          "slug": "w-c页面二级标题1"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3"
        },
        {
          "level": 2,
          "title": "w-c页面二级标题2",
          "slug": "w-c页面二级标题2"
        },
        {
          "level": 3,
          "title": "1.三级标题1",
          "slug": "_1-三级标题1-2"
        },
        {
          "level": 3,
          "title": "2.三级标题2",
          "slug": "_2-三级标题2-2"
        },
        {
          "level": 3,
          "title": "3.三级标题3",
          "slug": "_3-三级标题3-2"
        }
      ],
      "lastUpdated": "2023年3月1日星期三下午12点33分",
      "lastUpdatedTimestamp": 1677645233000
    },
    {
      "title": "Hello VuePress：",
      "frontmatter": {},
      "regularPath": "/%E5%BC%80%E5%8F%91%E8%AE%B0%E5%BD%95.html",
      "relativePath": "开发记录.md",
      "key": "v-1ead3dbc",
      "path": "/%E5%BC%80%E5%8F%91%E8%AE%B0%E5%BD%95.html",
      "lastUpdated": "2023年3月1日星期三晚上7点24分",
      "lastUpdatedTimestamp": 1677669880000
    }
  ],
  "themeConfig": {
    "lastUpdated": "更新时间",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "关于",
        "link": "/about"
      },
      {
        "text": "内关于",
        "link": "/about/"
      },
      {
        "text": "pc",
        "link": "/pc/"
      },
      {
        "text": "phone",
        "link": "/phone/"
      },
      {
        "text": "百度",
        "link": "https://www.baidu.com",
        "target": "_blank"
      },
      {
        "text": "谷歌",
        "link": "https://google.com",
        "target": "_self",
        "rel": ""
      },
      {
        "text": "单列表",
        "ariaLabel": "单列表 Menu",
        "items": [
          {
            "text": "Chinese",
            "link": "/language/chinese/"
          },
          {
            "text": "Japanese",
            "link": "/language/japanese/"
          }
        ]
      },
      {
        "text": "列表分组",
        "items": [
          {
            "text": "分组1",
            "items": [
              {
                "text": "关于",
                "link": "/about"
              },
              {
                "text": "内关于",
                "link": "/about/"
              }
            ]
          },
          {
            "text": "分组2",
            "items": [
              {
                "text": "百度",
                "link": "https://www.baidu.com",
                "target": "_blank"
              },
              {
                "text": "谷歌",
                "link": "https://google.com",
                "target": "_self",
                "rel": ""
              }
            ]
          }
        ]
      }
    ],
    "sidebar": [
      "",
      "about",
      "about/",
      {
        "title": "web前端开发",
        "path": "/web/",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/web/w-a",
          "/web/w-b",
          "/web/w-c"
        ]
      }
    ]
  }
}